# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [13]:
import numpy as np

#original array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

#A border of 0's
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(padded_arr)



[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [28]:
expressions = [
    ("0 * np.nan", 0 * np.nan),
    ("np.nan == np.nan", np.nan == np.nan),
    ("np.inf > np.nan", np.inf > np.nan),
    ("np.nan - np.nan", np.nan - np.nan),
    ("np.nan in set([np.nan])", np.nan in set([np.nan])),
    ("0.3 == 3 * 0.1", 0.3 == 3 * 0.1)
]

for expr, val in expressions:
    print(f"{expr}: {val}")

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
matrix = np.diag([1, 2, 3, 4], k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [16]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1 
checkerboard[::2, 1::2] = 1 

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [17]:
arr = np.arange(6 * 7 * 8).reshape(6, 7, 8)
x, y, z = np.unravel_index(99, (6, 7, 8))

print(f"Index (x, y, z) of the 100th element: ({x}, {y}, {z})")

Index (x, y, z) of the 100th element: (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [18]:
base_pattern = np.array([[0, 1],
                         [1, 0]])

checkerboard = np.tile(base_pattern, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [19]:
matrix = np.random.randint(0, 10, size=(5, 5))

normalized = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print("Original:\n", matrix)
print("\nMin-max normalized [0, 1]:\n", normalized)

Original:
 [[6 4 0 9 5]
 [5 0 5 4 0]
 [5 3 5 6 3]
 [9 8 5 3 0]
 [5 2 2 7 1]]

Min-max normalized [0, 1]:
 [[0.66666667 0.44444444 0.         1.         0.55555556]
 [0.55555556 0.         0.55555556 0.44444444 0.        ]
 [0.55555556 0.33333333 0.55555556 0.66666667 0.33333333]
 [1.         0.88888889 0.55555556 0.33333333 0.        ]
 [0.55555556 0.22222222 0.22222222 0.77777778 0.11111111]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [20]:
color_dtype = np.dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

colors = np.array([(255, 0, 0, 255),  # Red
                   (0, 255, 0, 255),  # Green
                   (0, 0, 255, 255)], # Blue
                  dtype=color_dtype)

print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [21]:
A = np.random.rand(5, 3)

B = np.random.rand(3, 2)

C = A @ B

print("Matrix A (5x3):\n", A)
print("\nMatrix B (3x2):\n", B)
print("\nMatrix C (5x2) = A @ B:\n", C)


Matrix A (5x3):
 [[0.13043693 0.34838706 0.98168192]
 [0.12198891 0.00759476 0.41652122]
 [0.94917528 0.03652538 0.12153493]
 [0.92325514 0.9518974  0.28501733]
 [0.79431754 0.14755873 0.74674977]]

Matrix B (3x2):
 [[0.55137718 0.20565676]
 [0.17130755 0.71411978]
 [0.92001345 0.20955312]]

Matrix C (5x2) = A @ B:
 [[1.03476186 0.48132984]
 [0.45176807 0.11779473]
 [0.64142443 0.24675583]
 [0.9343488  0.9293687 ]
 [1.15026633 0.42521512]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [22]:
arr = np.array([1, 5, 9, 3, 8, 2, 7])

arr[(arr >= 3) & (arr <= 8)] *= -1

print(arr)

[ 1 -5  9 -3 -8  2 -7]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [29]:
#Author: Jake VanderPlass

print(sum(range(5), -1))
from numpy import*
print(sum(range(5), -1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [30]:

Z = np.array([1, 2, 3])
print(Z**Z)  

Z = np.array([1, 2, 3])
print(2 << Z)
print((2 << Z) >> 2) 

Z = np.array([1, -2, 3])
print(Z < -Z) 

Z = np.array([1, 2, 3])
print(1j * Z)

Z = np.array([1, 2, 3])
print(Z / 1 / 1)

try:
    print("Z < Z < Z:", Z < Z < Z)
except ValueError as e:
    print("Z < Z < Z: ValueError →", e)


[ 1  4 27]
[ 4  8 16]
[1 2 4]
[False  True False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]
Z < Z < Z: ValueError → The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [31]:
Z = np.array([1, 2, 3])

print("Z**Z:", Z**Z) 

print("2 << Z:", 2 << Z)    
print("2 << Z >> 2:", (2 << Z) >> 2)

print("1j * Z:", 1j * Z)

print("Z / 1 / 1:", Z / 1 / 1)

try:
    print("Z < Z < Z:", Z < Z < Z)
except ValueError as e:
    print("Z < Z < Z: ValueError →", e)


Z**Z: [ 1  4 27]
2 << Z: [ 4  8 16]
2 << Z >> 2: [1 2 4]
1j * Z: [0.+1.j 0.+2.j 0.+3.j]
Z / 1 / 1: [1. 2. 3.]
Z < Z < Z: ValueError → The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
import warnings

warnings.simplefilter("always", RuntimeWarning)

print("1. np.array(0) / np.array(0):")
with warnings.catch_warnings(record=True) as w:
    result1 = np.array(0) / np.array(0)
    print("   Result:", result1)
    if w:
        print("   Warning:", str(w[0].message))

print("\n2. np.array(0) // np.array(0):")
with warnings.catch_warnings(record=True) as w:
    result2 = np.array(0) // np.array(0)
    print("   Result:", result2)
    if w:
        print("   Warning:", str(w[0].message))

print("\n3. np.array([np.nan]).astype(int).astype(float):")
with warnings.catch_warnings(record=True) as w:
    result3 = np.array([np.nan]).astype(int).astype(float)
    print("   Result:", result3)
    if w:
        print("   Warning:", str(w[0].message))


1. np.array(0) / np.array(0):
   Result: nan

2. np.array(0) // np.array(0):
   Result: 0

3. np.array([np.nan]).astype(int).astype(float):
   Result: [-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [36]:
def round_away_from_zero(arr):
    arr = np.array(arr)  
    return np.where(arr > 0, np.ceil(arr), np.floor(arr))

a = np.array([1.2, -1.2, 2.7, -2.7, 0.0])
rounded = round_away_from_zero(a)
print(rounded)


[ 2. -2.  3. -3.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [37]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

common = np.intersect1d(a, b)
print(common)


[3 4 5]
