# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [12]:
print("NumPy Version:", np.__version__)
print("\nNumPy configuration:")
print(np.__config__.show())

NumPy Version: 2.3.0

NumPy configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.1",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/sc

c:\Users\Work\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [17]:
arr = np.array([6,8,9,11,13,45])
print(arr.nbytes)  
print(arr.size * arr.itemsize)  

48
48


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [19]:
help(np.add)


Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
vector=np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [24]:
vector1=np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [25]:
vector = np.arange(15,36 )
print("Original:", vector)

reversed_vector = vector[::-1]
print("Reversed:", reversed_vector)

Original: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
Reversed: [35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [27]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]
print(indices)

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
Identity_matrix=np.identity(3)
print(Identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
random_array = np.random.random((3, 3, 3))
print(random_array)

random_int_array = np.random.randint(0, 10, size=(3, 3, 3))
print(random_int_array)

[[[0.38960294 0.81337905 0.24379857]
  [0.61017289 0.69196385 0.8515681 ]
  [0.34011758 0.20989142 0.57999318]]

 [[0.243233   0.78933723 0.59374768]
  [0.93735467 0.02473988 0.34223341]
  [0.7731593  0.57903122 0.29951915]]

 [[0.13730665 0.81904901 0.53908421]
  [0.62497457 0.83761685 0.04306134]
  [0.29694562 0.30647451 0.45615044]]]
[[[9 5 7]
  [0 3 7]
  [2 2 8]]

 [[3 7 1]
  [5 6 4]
  [3 9 1]]

 [[1 8 0]
  [0 0 8]
  [4 8 5]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [31]:
arr = np.random.random((10, 10))

max_val = arr.max()
min_val = arr.min()

print("Array:\n", arr)
print("\nMaximum value:", max_val)
print("Minimum value:", min_val)


Array:
 [[9.60799418e-01 7.45638495e-01 5.49507093e-01 9.82364755e-01
  2.62481548e-01 5.20585505e-04 5.46317167e-01 6.93831966e-01
  7.95053318e-01 1.72773827e-02]
 [8.97133007e-01 8.54870287e-02 3.84701087e-01 4.96679580e-01
  6.95999103e-01 2.55062306e-01 1.79603484e-01 3.82291404e-01
  9.00391573e-01 2.94690795e-01]
 [5.59278741e-01 1.65196346e-01 2.10247911e-01 8.31220207e-01
  4.73438424e-01 5.43605130e-01 8.20604867e-01 2.51026716e-01
  4.55898618e-01 2.95148490e-01]
 [7.87210026e-01 8.99885004e-01 3.42084221e-01 4.90754242e-01
  6.99221400e-01 4.95465521e-01 3.41338978e-01 3.40187036e-01
  6.74970456e-02 3.58433075e-02]
 [5.36489449e-02 9.02633880e-01 3.33956873e-01 9.13639793e-01
  3.76141441e-01 8.42663984e-01 3.87627020e-01 6.09747919e-01
  2.68333206e-01 1.09382819e-02]
 [8.80905143e-01 1.32250022e-01 2.82665871e-01 9.60795225e-01
  8.17762005e-01 9.52874664e-01 7.28171882e-02 5.75717727e-01
  9.19802475e-01 7.43877753e-02]
 [7.91198008e-01 8.09132430e-01 3.67016381e-01 3.8

In [32]:
arr = np.random.randint(0, 100, size=(10, 10))

max_val = arr.max()
min_val = arr.min()

print("Array:\n", arr)
print("\nMaximum value:", max_val)
print("Minimum value:", min_val)


Array:
 [[47 91 80 80 36  5 85 31  9 36]
 [81 47 94 24 20 66 82 50 37 13]
 [62 67 53 47 90 82 18 84 77 22]
 [94 95 36 16 26  2 58 33 87 78]
 [21 85 12 15 11 86 83 66 16 49]
 [45 43 43 91 33  6 56 64 54 11]
 [99 62 70 44 10 99 15 64 45  3]
 [56 61 60 52 86 26 88 28 90 38]
 [60  5 43 20 60  1 73 49 87 85]
 [63 16 56 62 24 36 66 61 57  4]]

Maximum value: 99
Minimum value: 1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [33]:
vec = np.random.random(30) 
mean_value = vec.mean()

print("Vector:", vec)
print("Mean value:", mean_value)


Vector: [0.55062277 0.56731365 0.54207176 0.4491785  0.49202862 0.13977685
 0.10688537 0.10933159 0.36814102 0.13350859 0.33634164 0.38942785
 0.14861039 0.37818694 0.78825747 0.17058966 0.27445645 0.34184305
 0.38690167 0.15059078 0.24252423 0.32317087 0.24137119 0.37950944
 0.84963964 0.0740456  0.2355504  0.20232493 0.01389562 0.8873185 ]
Mean value: 0.3424471684872351


In [34]:
vec = np.random.randint(0, 100, 30)
mean_value = vec.mean()

print("Vector:", vec)
print("Mean value:", mean_value)


Vector: [30 23 73 41 86 54 20 28 54 72 76 22 25 20 77 93 66 78 59 94 25  0 68 23
 73 75 23  7 62 61]
Mean value: 50.266666666666666


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
arr = np.ones((9, 9), dtype=int) 
arr[1:-1, 1:-1] = 0       
print(arr)         

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]
