# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
import numpy as np
import warnings

warnings.filterwarnings('ignore')

print(np.array(0) / np.array(0))

np.seterr(all='ignore')

print(np.array(0) / np.array(0))  


nan
nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [9]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) 

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [7]:
import numpy as nump
dates = np.array([yesterday, today, tomorrow])
print("Date array:", dates)

Date array: ['2025-07-13' '2025-07-14' '2025-07-15']


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')  # First day of next month

July_dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print(July_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [10]:
A = np.array([1, 2, 3], dtype=np.float64)
B = np.array([4, 5, 6], dtype=np.float64)

result = A + B  
A /= -2         
result *= A    

print(result)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
#Create random array
np.random.seed(42)
arr = np.random.uniform(0, 100, size=5)
print("Original array:", arr)

# Method 1: np.trunc
result1 = np.trunc(arr)

# Method 2: astype(int)
result2 = arr.astype(int)

# Method 3: np.floor
result3 = np.floor(arr)

# Method 4: Subtraction method
result4 = arr - (arr % 1)

# Compare results
print("\nMethod 1 (trunc):", result1)
print("Method 2 (astype):", result2)
print("Method 3 (floor):", result3)
print("Method 4 (subtract):", result4)

print("\nAll methods equal?", 
      np.allclose(result1, result2) and 
      np.allclose(result1, result3) and 
      np.allclose(result1, result4))

Original array: [37.45401188 95.07143064 73.19939418 59.86584842 15.60186404]

Method 1 (trunc): [37. 95. 73. 59. 15.]
Method 2 (astype): [37 95 73 59 15]
Method 3 (floor): [37. 95. 73. 59. 15.]
Method 4 (subtract): [37. 95. 73. 59. 15.]

All methods equal? True


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [12]:
matrix = np.array([np.arange(5) for _ in range(5)])
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [16]:
import random
def generate_random_integers():
    for _ in range(10):
        yield random.randint(0, 100)

arr = np.fromiter(generate_random_integers(), dtype=int)
print("Random array:", arr)


Random array: [62 74 86 42 29 87 89 63 68 33]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [18]:
vec = np.random.uniform(low=0.0, high=1.0, size=10)
print("Random vector:", vec)


Random vector: [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914 0.61185289
 0.13949386 0.29214465 0.36636184 0.45606998]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [19]:
random_vector = np.random.random(10)

sorted_vector = np.sort(random_vector)

print("Original random vector:")
print(random_vector)
print("\nSorted vector:")
print(sorted_vector)

Original random vector:
[0.78517596 0.19967378 0.51423444 0.59241457 0.04645041 0.60754485
 0.17052412 0.06505159 0.94888554 0.96563203]

Sorted vector:
[0.04645041 0.06505159 0.17052412 0.19967378 0.51423444 0.59241457
 0.60754485 0.78517596 0.94888554 0.96563203]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [24]:
arr = np.array([1.0, 2.0, 3.0, 4.0])

total = sum(arr)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [25]:
A = np.random.rand(5)
B = np.random.rand(5)

equal = np.array_equal(A, B)
print("Arrays are exactly equal:", equal)

Arrays are exactly equal: False


#### 43. Make an array immutable (read-only) (★★☆)

In [26]:
arr = np.array([1, 2, 3, 4, 5])

arr.flags.writeable = False

try:
    arr[0] = 10  
except ValueError as e:
    print("Error:", e)  

Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [27]:
cartesian = np.random.rand(10, 2) * 10 - 5 

r = np.sqrt(cartesian[:, 0]**2 + cartesian[:, 1]**2)  
theta = np.arctan2(cartesian[:, 1], cartesian[:, 0])   

polar = np.column_stack((r, theta))

print("Cartesian coordinates:")
print(cartesian)
print("\nPolar coordinates (r, θ in radians):")
print(polar)

Cartesian coordinates:
[[ 1.62522284 -1.88288924]
 [ 0.20068021  0.46710279]
 [-3.15145544  4.69584628]
 [ 2.75132823  4.39498942]
 [ 3.9482735   0.97899979]
 [ 4.21874235 -4.11507498]
 [-3.04017138 -4.54772711]
 [-1.74669669 -1.1132271 ]
 [-2.28650968  3.28737509]
 [-1.43246673 -2.1906549 ]]

Polar coordinates (r, θ in radians):
[[ 2.48729194 -0.85871525]
 [ 0.50838722  1.16501267]
 [ 5.65531995  2.1618726 ]
 [ 5.185146    1.01146763]
 [ 4.06783779  0.24305438]
 [ 5.89335466 -0.77295944]
 [ 5.47032576 -2.16006949]
 [ 2.07128557 -2.57417392]
 [ 4.00436781  2.17852453]
 [ 2.6174281  -2.14990751]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [28]:
vec = np.random.rand(10) 
print("Original vector:", vec)

max_index = np.argmax(vec)

vec[max_index] = 0
print("Modified vector:", vec)


Original vector: [0.54269608 0.14092422 0.80219698 0.07455064 0.98688694 0.77224477
 0.19871568 0.00552212 0.81546143 0.70685734]
Modified vector: [0.54269608 0.14092422 0.80219698 0.07455064 0.         0.77224477
 0.19871568 0.00552212 0.81546143 0.70685734]
